//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.20 at 07:35:39 PM SAMT 
//


package com.example.bank.xmlEntity;

import lombok.Data;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ED807Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ED807Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BICDirectoryEntry" type="{urn:cbr-ru:ed:v2.0}BICDirectoryEntryType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="EDNo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EDDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="EDAuthor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CreationReason" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CreationDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="InfoTypeCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BusinessDay" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="DirectoryVersion" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ED807Type", propOrder = {
    "bicDirectoryEntry"
})
@Data
public class ED807Type {

    @XmlElement(name = "BICDirectoryEntry")
    protected List<BICDirectoryEntryType> bicDirectoryEntry;
    @XmlAttribute(name = "EDNo")
    protected String edNo;
    @XmlAttribute(name = "EDDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar edDate;
    @XmlAttribute(name = "EDAuthor")
    protected String edAuthor;
    @XmlAttribute(name = "CreationReason")
    protected String creationReason;
    @XmlAttribute(name = "CreationDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationDateTime;
    @XmlAttribute(name = "InfoTypeCode")
    protected String infoTypeCode;
    @XmlAttribute(name = "BusinessDay")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar businessDay;
    @XmlAttribute(name = "DirectoryVersion")
    protected Integer directoryVersion;

    public List<BICDirectoryEntryType> getBICDirectoryEntry() {
        if (bicDirectoryEntry == null) {
            bicDirectoryEntry = new ArrayList<BICDirectoryEntryType>();
        }
        return this.bicDirectoryEntry;
    }
}
