//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.20 at 07:35:39 PM SAMT 
//


package com.example.bank.xmlEntity;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.cbr.ed.v2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ED807_QNAME = new QName("urn:cbr-ru:ed:v2.0", "ED807");
    private final static QName _ParticipantInfoTypeRstrList_QNAME = new QName("urn:cbr-ru:ed:v2.0", "RstrList");
    private final static QName _AccountsTypeAccRstrList_QNAME = new QName("urn:cbr-ru:ed:v2.0", "AccRstrList");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.cbr.ed.v2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ED807Type }
     * 
     */
    public ED807Type createED807Type() {
        return new ED807Type();
    }

    /**
     * Create an instance of {@link ParticipantInfoType }
     * 
     */
    public ParticipantInfoType createParticipantInfoType() {
        return new ParticipantInfoType();
    }

    /**
     * Create an instance of {@link SWBICSType }
     * 
     */
    public SWBICSType createSWBICSType() {
        return new SWBICSType();
    }

    /**
     * Create an instance of {@link AccRstrListType }
     * 
     */
    public AccRstrListType createAccRstrListType() {
        return new AccRstrListType();
    }

    /**
     * Create an instance of {@link AccountsType }
     * 
     */
    public AccountsType createAccountsType() {
        return new AccountsType();
    }

    /**
     * Create an instance of {@link RstrListType }
     * 
     */
    public RstrListType createRstrListType() {
        return new RstrListType();
    }

    /**
     * Create an instance of {@link BICDirectoryEntryType }
     * 
     */
    public BICDirectoryEntryType createBICDirectoryEntryType() {
        return new BICDirectoryEntryType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ED807Type }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cbr-ru:ed:v2.0", name = "ED807")
    public JAXBElement<ED807Type> createED807(ED807Type value) {
        return new JAXBElement<ED807Type>(_ED807_QNAME, ED807Type.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RstrListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cbr-ru:ed:v2.0", name = "RstrList", scope = ParticipantInfoType.class)
    public JAXBElement<RstrListType> createParticipantInfoTypeRstrList(RstrListType value) {
        return new JAXBElement<RstrListType>(_ParticipantInfoTypeRstrList_QNAME, RstrListType.class, ParticipantInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AccRstrListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:cbr-ru:ed:v2.0", name = "AccRstrList", scope = AccountsType.class)
    public JAXBElement<AccRstrListType> createAccountsTypeAccRstrList(AccRstrListType value) {
        return new JAXBElement<AccRstrListType>(_AccountsTypeAccRstrList_QNAME, AccRstrListType.class, AccountsType.class, value);
    }

}
